{% set version = "1.5.4" %}

package:
  name: thredds_crawler
  version: {{ version }}

source:
  url: https://github.com/ioos/thredds_crawler/archive/{{ version }}.tar.gz
  sha256: 508426b6931c790ae6124453c1ef862f533fe867a122ea6ade85bcc44b78ff85

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - lxml
    - netcdf4
    - pytz

test:
  imports:
    - thredds_crawler

about:
  home: https://github.com/ioos/thredds_crawler
  license: MIT
  summary: 'A Python library for crawling THREDDS servers.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
