travis:
  secure:
    BINSTAR_TOKEN: xOOuhyAn42MGZ0hLOT0wqtJ9qev08fhEct+eEiAW21oh7FkptXCctFvt5aK3vZOGjs8k1mZLDb6q714qynryVOqpJ68OvZ2YLthYZ2YPwq76GveL1exLSbE5sFPNmqbccJxP73wmch2d3LpqdY6CAXHSC4BJQdcE7VyhjCU6xptPUj0MhA6XP7RSeEzoI5ADxpPgUB0luHMxhP9oVeuhpovp8oq1dpFewYC1FrI8S8b4ULCm71p6WW0BRMgX5REkPdgmMjb1egusYylNQ1iWP1fx9gW9kpaKlWwrU2ilnWI3bm6wg4YCPgyw7Is/Qj8RtqpKhakQCVTb06l7KsIrFInD79KeiDjTIiqqxyjJPcFhq4AkdKXziYq7nT9TzNOZSrA9bfltBk4Tw5K0EDkALLQVhZ67kM+k64/5PC/s5gqqi6ixWFKeORKLk8Kbsrby8Bx7fmKGNaVTbGDtkNvv8be+n3/xJ5nkQkhgldR3EO+4AM6p4/YIgO65NFrmh/Z4hzsj9K3XylUlBGvIgVnLJPMtauCBQzn+AtrLn6n81AYEy5yFcQTyfmi7eUKSQjaiFY/F/cSfinaMyMWPD1LGLKsoavEBd1QDbQP/6W87WsEP0mVRbNguG9RZBOU+sVFglajcLTlXievvWOThVPYvzG9n4GwzPjZniGTm7TrlI0g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
