travis:
  secure:
    BINSTAR_TOKEN: 4UergEDgV0eaXU05yL8LxDZq1+io2E+zPqp6noqzDTUZAfoTSxWK8Rr+QYOicGzROHPW3+7oahhKBWcb+D3AL6gx6vpUEQyvh5ITM9pqrT3Dzs6ut6orQveZsthoIuZiI/iuaA15I4SpYZRP19oQgcItcmou1VEvuIwhWp/VvuPZSIwyljuJdR6xjrBxAnjzUC3Z4G78lA3aPcSCdcXm7qUeLLPusexhiK1ZWakeVQYh7REVZpsao73ribHSmnSEWwQZaX3LbVBaSOZdvN8QwAZ0yKb4txOgjusb1xWasicqCyxtiwlnBLavNVCd+5AhAm7Ofr/VgzKJn53cRviyOlcLPSjKDr5qVXmShRHxDMdrGmIpTl9GoAhCXX9doi6CwoRlXmcxPdb76kMQAEO+eJpqxf290h1VwHkxgZnUvwPTzNxouaqy+1rkgL2jXMsL6qYUTPuYZKwxCCpMuZJ2K27n/NZJMxAdqh/gcPnuRm71KWFU/IdGPO/qcdWu4yloDX7SHNT5y6/SA7J8hslOWxMCCJ0U8ZkcZ8ivZYu72Vz3aTLRRcEq+/EY02UFUOz586yg0xgOTkMvfN0Cum4bxemvrzSjJA8vvBtZpC3klov7uMXTXBMljfKNJ2QMxAtVKK4QTCbFF1EdCLeQM6FRZI77WAQy7hLUjY/RR78W6ac=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
